# Generated by Django 6.0.2 on 2026-03-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('foto', models.ImageField(null=True, upload_to='fotos/', verbose_name='Foto')),
                ('clase', models.TextField(null=True, verbose_name='Clase')),
            ],
        ),
    ]
